require("prototypes.entity.entities-final-fixes")
require("prototypes.entity.explosions-final-fixes")
require("prototypes.entity.remnants-final-fixes")
require("prototypes.item-final-fixes")
require("prototypes.recipe-final-fixes")
